import Head from "next/head";
import Hero from "../components/Hero.js";
import SingIn from "../components/SingIn.js";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>BET FRIENDS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
        </Head>
      </div>

      <Hero />
      <SingIn />
    </>
  );
}
