import Head from "next/head";
import Hero from "../components/Hero.js";
import SingIn from "../components/SingIn.js";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>BET FRIENDS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;900&family=Merriweather&family=Merriweather+Sans:wght@700&family=Montserrat:wght@100;400;900&family=Open+Sans:wght@300&family=Sacramento&family=Ubuntu:ital,wght@0,300;0,400;1,500&family=Work+Sans:wght@300;400;500&display=swap"
            rel="stylesheet"
          />
        </Head>
      </div>

      <Hero />
      <SingIn />
    </>
  );
}
